### ISSUE TITLE
Add export (and maybe import) options

### ISSUE THREAD

**Issue by louisfoster** [carlosfelipespinola/flashcards#18]
Cool app!
I was hoping to be able to easily export and import the data from within the app so I can share and backup flashcards. I'm using the android version. A JSON or CSV file would be perfect, and actually, only export is really necessary to start with.

If you don't have time, I don't mind adding the feature to this repo in a PR if you're able to release the feature in a version update. Just let me know!

- thanks!

**Comment by carlosfelipespinola** [comment]
Hi there, thanks for your feedback! 

I will add this feature to my backlog and implement it as soon as i can

**Comment by carlosfelipespinola** [comment]
Closing issue. Import and export feature was implemented and the rollout to production was started today. The file that is exported by the app is a json lines file.
